### ISSUE TITLE
Consider removing mimics enemies by default

### ISSUE THREAD

**Issue by ratijas** [qwbarch/mirage#58]
Our team decided to give this mod a try, replacing the famous non-syncing Skinwalkers mod. This one is presented as basically a drop-in replacement, its description reads:

> Synced voice mimicking for any enemy (all players hear the same voice). This is a standalone mod and does not require Skinwalkers to work.

However, we totally did not expect this mod to be messing with mimics enemies by default, especially giving them our players' appearance. It was just not fun getting blasted by a horde of zombies day after day. We quickly got annoyed by these early mimics spawns, and we just toggled the mod of instead of wasting time figuring out the config options.

If this is a replacement for Skinwalkers, and a "synced voice mimicking", why is it affecting the enemies spawns by default? That's like two totally different mods in one. Please, consider splitting in actual two packages, or at least disable the mimics by default.

**Comment by qwbarch** [comment]
That's fair, I'll turn them off by default on the next update

**Comment by qwbarch** [comment]
In the meantime if you want vanilla spawns, you'll want to set ``EnableOverrideSpawnChance`` to ``false``, and ``SpawnOnPlayerDeath`` to ``0`

**Comment by qwbarch** [comment]
I've decided to keep the current defaults since Mirage is not meant to by a drop-in replacement for Skinwalkers, and clarified it in the mod description and README.

I've also added an FAQ [section](https://github.com/qwbarch/mirage/tree/production#why-does-this-mod-come-with-so-many-features-i-only-want-skinwalkers-but-with-synced-voices) that shows what configuration options to change in order to make it more like Skinwalkers.

**Comment by ratijas** [comment]
> Mirage is not meant to by a drop-in replacement for Skinwalkers

riiiiiiight 🫠

but oh well, your mod, your call
