### ISSUE TITLE
[Bug] Mirage is saving some fake player voice lines

### ISSUE THREAD

**Issue by ajsglist** [qwbarch/mirage#65]
Hey there,

I thought Mirage had broken, but when I dug into it, it turned out it had been recording a few too many "empty" player voice lines for a few of us.  I *think* it has to do with mirage picking up low levels of mic activity a bit too aggressively, but I can't say for sure.

When I looked in the mirage folder, I saw a ton of voice lines that were as expected.  But I also found a bunch of essentially empty clips at the bottom when sorted by file size.  At first glance, it seems like everything below 100kb is bad.  Perhaps a lower limit on file size for "good" player voice lines?

![image](https://github.com/qwbarch/mirage/assets/139426529/37bf3155-c5c6-418b-a53f-9e450951f335)

**Comment by qwbarch** [comment]
This is a problem with voice activity in general, if you've ever used Skinwalkers, it contains even more empty voice clips, whereas in Mirage I set a minimum audio length to try to remove most of the empty clips.

In the upcoming v2 update, it's fixed by using [SileroVAD](https://github.com/snakers4/silero-vad).
