### ISSUE TITLE
issues with mirage update 1.9.2. [LETHAL COMPANY]

### ISSUE THREAD

**Issue by RednaXSW** [qwbarch/mirage#82]
Mirage 1.9.2. still causes my game to freeze and then crash. i hope it can be fixed!

**Comment by dmb1996** [comment]
I second this, seems there is now a MirageCore dependency that is not available on r2modman. The icon seems to have updated in the store but not in the library after downloading,

**Comment by qwbarch** [comment]
Sorry about that, you need ``MirageCore v1.0.1`` for it to not crash

**Comment by ZetaMLG** [comment]
Mirage 1.9.2 does not generate the configuration files and it also does not appear to configure it within the game.

**Comment by qwbarch** [comment]
If you can see ``Mirage.General.cfg`` and ``Mirage.Enemies.cfg``, that means it *did* generate properly.  
I did forget to write in the README that players need to load into the game once (not just in the main menu, but actually inside the game itself), since ``Mirage.Enemies.cfg`` picks up the list of monsters at runtime to generate it

**Comment by FettysTown** [comment]
My friends and I are having a problem synchronizing voices on mobs.... Installed everything as specified, double-checked several times, copied the files for config, but to no avail

**Comment by qwbarch** [comment]
Closing this issue as it's already been fixed
