### ISSUE TITLE
New config files not generating

### ISSUE THREAD

**Issue by NineOfGaming** [qwbarch/mirage#84]
the mod does not generate the new config files (Mirage.General.cfg and Mirage.Enemies.cfg)

**Comment by qwbarch** [comment]
``Mirage.General.cfg`` generates after launching the game. For ``Mirage.Enemies.cfg``, this is only generated after you host a game, since it pulls the enemies at run-time.

**Comment by NineOfGaming** [comment]
mfw closed without waiting for a response

i did not only start the game several times, i also played through several quotas.
no config files.

**Comment by qwbarch** [comment]
Sorry I was just trying to clean up the issues tab since there were so many opened recently.
Can you double check if the ``Bepinex/config`` folder not contain any of the mirage configs? This doesn't seem possible unless Mirage didn't run at all, which in that case you should have errors if Mirage failing to initialize on startup

**Comment by NineOfGaming** [comment]
It seems thats the case, tho i also dont even get any error messages related to Mirage which is strange, almost like its just being completely skipped for some reason.

are there by any chance any known incompatabilities that could potentially cause Mirage to not load?

**Comment by estase3** [comment]
Well, for any future readers, files are generated at  `\AppData\Roaming\r2modmanPlus-local\LethalCompany\profiles\Default\BepInEx\config\`. I think it's worth adding it to readme - I first thought they should be in the Mirage folder in game dir
