### ISSUE TITLE
Potential Memory Leak or Large Lag Issue?

### ISSUE THREAD

**Issue by Lincolnium** [qwbarch/mirage#86]
It seems after updating to the most recent major update of Mirage I've been having a lot more lag. The lag only starts happening after around 30 minutes of gameplay, and mostly when I'm with 1-3 other people. I'm definitely not sure if it is mirage or not, but I just assume it is due to the complexity of the mod. I'm running a lower end PC, so it takes my frames down from 40ish at the beginning of a session all the way down to around 10-6ish. 01923cab-a1e5-df14-6eaf-5c11d1622ff0

Edit: The only other large mod I could think it would maybe be would be Lethal Casino, I added it to my pack around that time

**Comment by qwbarch** [comment]
I don't think this is an issue with Mirage, otherwise it would've came up during the many experimental builds I've had others test.
If you'd like you can use the old version ``1.8.2`` which has been stable for a long time. Make sure you have ``BarchLib`` installed and have ``MirageCore`` uninstalled though.
